name: "GitHub Runner PR Check"
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - "cdk/**"
permissions:
  pull-requests: write
  id-token: write
  contents: write
jobs:
  pr-check:
    name: pr check
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        environment: ops-dev
        include:
        # Add a new environment block below for each environment context added to the CDK.
          - environment: ops-dev
            assume_role: arn:aws:iam::123456789100:role/githubActionsOidc
            region: us-east-1
    defaults:
      run:
        shell: bash
        working-directory: cdk
    steps:
      - name: checkout
        uses: actions/checkout@v3
        id: checkout
      - name: setup node
        uses: actions/setup-node@v3
        id: set-node
        with:
          node-version: "16"
          check-latest: true
      - name: configure credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ matrix.assume_role }}
          role-duration-seconds: 1200
          aws-region: ${{ matrix.region }}
      - name: install dependencies
        id: npm-i
        run: npm install
      - name: run diff
        id: diff
        run: |
          echo -e "<details>\n<summary>:zap: Diff Output</summary>\n\n\`\`\`\n" > diff.out
          npx cdk diff "*" -c config=$ENVIRONMENT --no-color --ci >> diff.out
          echo -e "\`\`\`\n</details>\n" >> diff.out
        env:
          ENVIRONMENT: ${{ matrix.environment }}
      - name: pr comment
        id: pr-comment
        if: ${{ always() && !cancelled() && github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.number }}
        run: |
          gh pr comment $PR --body-file diff.out
